### ISSUE TITLE
Related projects

### ISSUE THREAD

**Issue by pixeltris** [2427dkusiro/WasmCSharpEditor#2]
Hi, this isn't really an issue. I recently finished a similar project (https://github.com/pixeltris/webcs) and I stumbled across yours after doing a bit of searching on github. Your project is really cool.

I like your implementation of `Console.ReadLine`. I opted to do everything in the main thread so I had to skip that one and created a callback based alternative.

Here are some other projects I found on my search:

- https://github.com/nbarkhina/CSharp-In-Browser
- https://github.com/Suchiman/Runny
- https://github.com/sapsari/website-blazor-demo
- https://github.com/fsbolero/TryFSharpOnWasm - F#
- https://github.com/amieres/FSharpStation - F# (not sure if working)

It's interesting that client side compilation has been possible for quite a few years now but nobody has taken the idea further (i.e. a full IDE). It's definitely possible. I don't have any plans to take on the task, but I look forward to seeing who does. It would be cool to see client side compilation integrated into something like https://vscode.dev or https://github.dev

**Comment by 2427dkusiro** [comment]
Thank you very much for your interest in my project.

Implementing `Console.ReadLine` like a real console was one of the most difficult tasks in this project, so I am glad you appreciate this.

I would like to use the related projects you presented and your own project as a reference for future development.

Thank you very much for your contribution.
